from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any, Dict, List, Mapping, Optional

from agent_mode_utils import (
    AGENT_RUNS_ROOT,
    append_run_index,
    default_timeout,
    ensure_run_root,
    make_run_id,
    now_local,
    prepare_sandbox_workspace,
    read_agent_policy,
    resolve_agent_command,
    run_agent_command,
    safe_rel,
    write_manifest,
    write_protected_snapshot,
    write_run_copy_risk,
)
from benchmark_agent_run import benchmark_run, find_or_build_draft
from validate_agent_run import validate_run
from workflow_utils import ROOT, dump_yaml, load_yaml, read_state


def write_training_prompt(run_dir: Path, workspace: Path, max_iterations: int) -> Path:
    prompt = workspace / "agent_prompt.md"
    text = f"""# Agent Training Sandbox Task

You are operating inside a sandbox workspace, not the formal project root.

Workspace: `{workspace}`
Max iterations: {max_iterations}

Rules:
- Use deep_sequential order only.
- Do not write outside this workspace.
- Do not copy prior paper abstracts, body text, captions, tables, or conclusions.
- Generate outputs only from code, contracts, and sandbox artifacts.
- Keep result numbers in `14_contracts/result_contract.csv`.
- Keep claims in `14_contracts/claim_evidence_map.csv`.
- Keep figures in `14_contracts/figure_contract.csv` and cite only existing files.
- After a draft exists, use local prior DB only for gap comparison, not as an answer key.

Suggested command sequence:
1. Inspect `workflow_state.yaml`, `00_problem/`, `03_data/`, and `prompts/stages/`.
2. Run one stage at a time through `python scripts/run_current_stage.py --stage current`.
3. Stop at any human gate marker inside the sandbox and write the blocker into `11_review/`.
4. Produce or assemble `09_paper/full_draft.md`.
5. Record review issues in `11_review/` and `14_contracts/revision_tasks.csv`.

Final expected sandbox artifacts:
- `09_paper/full_draft.md`
- `14_contracts/result_contract.csv`
- `14_contracts/claim_evidence_map.csv`
- `14_contracts/figure_contract.csv`
- `11_review/review_scorecard.csv`
- `14_contracts/revision_tasks.csv`
"""
    prompt.write_text(text, encoding="utf-8")
    (run_dir / "agent_prompt.md").write_text(text, encoding="utf-8")
    return prompt


def write_iteration_prompt(run_dir: Path, workspace: Path, iteration: int) -> Path:
    queue = run_dir / "reports" / "agent_revision_queue.csv"
    prompt = workspace / f"agent_iteration_{iteration:02d}_prompt.md"
    text = f"""# Agent Training Iteration {iteration}

Use the structured revision queue at:
`{queue}`

Work only inside:
`{workspace}`

Tasks:
- Address open fail/major items first.
- Preserve result numbers unless regenerated by executable sandbox code.
- Update contracts before updating draft text.
- Do not copy prior-paper text.
- Leave unresolved items open with a clear blocker note.
"""
    prompt.write_text(text, encoding="utf-8")
    return prompt


def update_status(run_dir: Path, status: str, extra: Optional[Mapping[str, Any]] = None) -> Path:
    payload: Dict[str, Any] = {"status": status, "updated_at": now_local()}
    if extra:
        payload.update(dict(extra))
    return write_manifest(run_dir, payload)


def run_training_sandbox(args: argparse.Namespace, policy: Mapping[str, Any]) -> int:
    ensure_run_root()
    run_id = args.run_id or make_run_id("training_sandbox")
    run_dir = AGENT_RUNS_ROOT / run_id
    run_dir.mkdir(parents=True, exist_ok=True)
    (run_dir / "reports").mkdir(exist_ok=True)
    (run_dir / "logs").mkdir(exist_ok=True)
    snapshot = write_protected_snapshot(run_dir, policy)
    workspace = prepare_sandbox_workspace(run_dir, Path(args.problem) if args.problem else None, policy)
    max_iterations = args.max_iterations or int(((policy.get("training_sandbox") or {}).get("max_iterations")) or 3)
    prompt = write_training_prompt(run_dir, workspace, max_iterations)
    manifest = write_manifest(
        run_dir,
        {
            "run_id": run_id,
            "mode": "training_sandbox",
            "status": "created",
            "created_at": now_local(),
            "workspace": safe_rel(workspace),
            "problem": args.problem,
            "max_iterations": max_iterations,
            "formal_protected_snapshot": safe_rel(snapshot),
            "agent_prompt": safe_rel(prompt),
        },
    )

    cmd = resolve_agent_command(policy, prompt, workspace, run_dir, "training_sandbox", max_iterations)
    if args.dry_run:
        status = "dry_run"
        update_status(run_dir, status, {"agent_command_present": bool(cmd), "dry_run": True})
    elif not cmd:
        status = "needs_agent_executor"
        update_status(run_dir, status, {"agent_command_present": False, "fallback": args.fallback})
    else:
        rc, tail = run_agent_command(cmd, workspace, run_dir / "logs" / "agent_initial.log", default_timeout(policy))
        status = "agent_passed" if rc == 0 else "agent_failed"
        update_status(run_dir, status, {"agent_command_present": True, "initial_exit_code": rc, "initial_log_tail": tail})
        if rc != 0:
            benchmark = benchmark_run(run_id)
            validation = validate_run(run_id)
            append_run_index(run_id, "training_sandbox", status, workspace, manifest, run_dir / "reports" / "full_gap_report.md", "agent command failed")
            print(json.dumps({"run_id": run_id, "status": status, "benchmark": benchmark, "validation": validation}, ensure_ascii=False, indent=2))
            return 1

    benchmark = benchmark_run(run_id)

    if cmd and not args.dry_run and status == "agent_passed":
        for iteration in range(2, max_iterations + 1):
            queue_path = run_dir / "reports" / "agent_revision_queue.csv"
            if not queue_path.exists() or queue_path.stat().st_size <= 4:
                break
            iter_prompt = write_iteration_prompt(run_dir, workspace, iteration)
            iter_cmd = resolve_agent_command(policy, iter_prompt, workspace, run_dir, "training_sandbox", max_iterations)
            rc, tail = run_agent_command(iter_cmd, workspace, run_dir / "logs" / f"agent_iteration_{iteration:02d}.log", default_timeout(policy))
            update_status(run_dir, "iteration_failed" if rc else "iteration_passed", {f"iteration_{iteration}_exit_code": rc, f"iteration_{iteration}_log_tail": tail})
            benchmark = benchmark_run(run_id)
            if rc != 0:
                break

    draft_path, draft_status = find_or_build_draft(workspace)
    copy_risk_payload: Dict[str, Any] = {"copy_risk": "skipped_no_draft"}
    if draft_path.exists() and draft_status != "missing":
        copy_csv, copy_md, copy_rows = write_run_copy_risk(run_dir, draft_path, policy)
        copy_risk_payload = {
            "copy_risk": copy_rows[0].get("decision"),
            "copy_risk_report": safe_rel(copy_csv),
            "copy_risk_markdown": safe_rel(copy_md),
        }

    final_status = status
    if status == "agent_passed":
        final_status = "completed"
    update_status(run_dir, final_status, {"benchmark": benchmark, **copy_risk_payload})
    validation = validate_run(run_id)
    append_run_index(run_id, "training_sandbox", final_status, workspace, manifest, run_dir / "reports" / "full_gap_report.md")
    print(json.dumps({"run_id": run_id, "status": final_status, "benchmark": benchmark, "validation": validation}, ensure_ascii=False, indent=2))
    return 0 if not validation.get("fail_count") else 1


def formal_stage_prompt(current_stage: str, pending_gate: str, stage_prompt_text: str) -> str:
    return f"""# Formal Assist Task

You are assisting the formal deep_sequential workflow.

Current stage: `{current_stage}`
Pending gate before run: `{pending_gate or 'none'}`

Rules:
- Do not run `--stage all`.
- Do not call `scripts/confirm_gate.py`.
- Use only the current stage path through `python scripts/run_current_stage.py --stage current`.
- Stop immediately if a pending gate appears.
- Do not bypass contract validation.

Stage prompt:

```markdown
{stage_prompt_text}
```
"""


def resolve_stage_prompt_file(current_stage: str) -> Path:
    direct = ROOT / "prompts" / "stages" / f"{current_stage}.md"
    if direct.exists():
        return direct
    matches = sorted((ROOT / "prompts" / "stages").glob(f"*_{current_stage}.md"))
    return matches[0] if matches else direct


def run_formal_assist(args: argparse.Namespace, policy: Mapping[str, Any]) -> int:
    ensure_run_root()
    run_id = args.run_id or make_run_id("formal_assist")
    run_dir = AGENT_RUNS_ROOT / run_id
    run_dir.mkdir(parents=True, exist_ok=True)
    (run_dir / "reports").mkdir(exist_ok=True)
    (run_dir / "logs").mkdir(exist_ok=True)
    state_before = read_state()
    current_stage = str(state_before.get("current_stage") or "")
    pending_gate = str(state_before.get("pending_gate") or "")
    prompt_file = resolve_stage_prompt_file(current_stage)
    stage_prompt_text = prompt_file.read_text(encoding="utf-8", errors="ignore") if prompt_file.exists() else ""
    prompt = run_dir / "formal_agent_prompt.md"
    prompt.write_text(formal_stage_prompt(current_stage, pending_gate, stage_prompt_text), encoding="utf-8")
    manifest = write_manifest(
        run_dir,
        {
            "run_id": run_id,
            "mode": "formal_assist",
            "status": "created",
            "created_at": now_local(),
            "formal_root": safe_rel(ROOT),
            "current_stage_before": current_stage,
            "pending_gate_before": pending_gate,
            "agent_prompt": safe_rel(prompt),
        },
    )
    cmd = resolve_agent_command(policy, prompt, ROOT, run_dir, "formal_assist", 1)
    if args.dry_run:
        status = "dry_run"
        update_status(run_dir, status, {"agent_command_present": bool(cmd), "dry_run": True})
    elif not cmd:
        status = "needs_agent_executor"
        update_status(run_dir, status, {"agent_command_present": False, "fallback": args.fallback})
    else:
        rc, tail = run_agent_command(cmd, ROOT, run_dir / "logs" / "formal_agent.log", default_timeout(policy))
        status = "agent_passed" if rc == 0 else "agent_failed"
        update_status(run_dir, status, {"exit_code": rc, "log_tail": tail})

    state_after = read_state()
    report = run_dir / "reports" / "formal_assist_report.md"
    lines = [
        "# Formal Assist Report",
        "",
        f"- run_id: {run_id}",
        f"- status: {status}",
        f"- current_stage_before: {current_stage}",
        f"- pending_gate_before: {pending_gate or 'none'}",
        f"- current_stage_after: {state_after.get('current_stage')}",
        f"- pending_gate_after: {state_after.get('pending_gate') or 'none'}",
        "",
        "Formal assist never confirms human gates. If `pending_gate_after` is not none, human review is required.",
    ]
    report.write_text("\n".join(lines) + "\n", encoding="utf-8")
    update_status(run_dir, status, {"formal_assist_report": safe_rel(report), "pending_gate_after": state_after.get("pending_gate")})
    append_run_index(run_id, "formal_assist", status, ROOT, manifest, report)
    print(json.dumps({"run_id": run_id, "status": status, "report": safe_rel(report)}, ensure_ascii=False, indent=2))
    return 0 if status != "agent_failed" else 1


def main() -> None:
    parser = argparse.ArgumentParser(description="Run agent-mode training sandbox or formal assist.")
    parser.add_argument("--mode", choices=["training_sandbox", "formal_assist"], default="")
    parser.add_argument("--problem", default="00_problem/problem_statement.md")
    parser.add_argument("--max-iterations", type=int, default=0)
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--fallback", default="prompt_bundle")
    parser.add_argument("--run-id", default="")
    args = parser.parse_args()

    policy = read_agent_policy()
    mode = args.mode or str(policy.get("default_mode") or "training_sandbox")
    if mode == "training_sandbox":
        raise SystemExit(run_training_sandbox(args, policy))
    if mode == "formal_assist":
        raise SystemExit(run_formal_assist(args, policy))
    raise SystemExit(f"[FAIL] unknown mode: {mode}")


if __name__ == "__main__":
    main()
